name: Project Build

on:
  pull_request: { }
  workflow_dispatch: { }
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check project
        run: ./gradlew check --continue

      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.repository == 'bnorm/storyboard'
    needs: [ build ]

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish SNAPSHOT
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
